---
  - name: check package list
    tags: install,find_package
    find: paths={{ publish_library }} use_regex=True patterns="^{{ java_package}}"
    register: pkg_files
    delegate_to: 127.0.0.1
    failed_when: pkg_files.matched == 0

  - name: get the package name
    tags: install,find_packge
    #vars:
      #- pkg_file_name: "{{ pkg_files.files | sort(attribute='path', reverse=True, case_sensitive=False) | map(attribute='path') | list | first}}"
    shell: echo "{{ pkg_files.files | sort(attribute='path', reverse=True, case_sensitive=False) | map(attribute='path') | list | first}}"
    register: pkg_file_name
    delegate_to: 127.0.0.1
    changed_when: False

  - debug: msg="package = {{ pkg_file_name.stdout }}"
    tags: install,find_package
    delegate_to: 127.0.0.1

  - name: sync installation package
    tags: install
    copy: src={{ pkg_file_name.stdout }} dest={{ remote_pkgs_library }}/

  #- name: link installation package
    #tags: install
    #sudo: yes
    #file: src="{{ remote_pkgs_library }}/{{ pkg_file_name.stdout | basename }}" dest={{ remote_pkgs_library }}/java.used state=link

  - name: install package
    tags: install
    sudo: yes
    vars:
      - src_pkg_full_path: "{{ remote_pkgs_library }}/{{ pkg_file_name.stdout | basename }}"
    shell: >
      mkdir -p {{ java_install_root }} && cd {{ java_install_root }}
      && pkg_name=`tar -tzf {{ src_pkg_full_path }} | head -1 | cut -d "/" -f 1`
      && rm -rf ${pkg_name}
      && tar -xzf {{ src_pkg_full_path }}
      && ln -s -f -T ${pkg_name} {{java_home}}
      warn=no

  #- name: set env
    #tags: install
  #  shell: |
  #    file="${HOME}/.bashrc"
  #    message1='export JAVA_HOME=/usr/java/default'
  #    grep "^${message1}$" "${file}" >>/dev/null
  #    if [ $? -ne 0 ]
  #    then
  #        echo "${message1}" >> "${file}"
  #    fi
  #    message2='export PATH=${JAVA_HOME}/bin:${PATH}'
  #    grep "^${message2}$" "${file}" >>/dev/null
  #    if [ $? -ne 0 ]
  #    then
  #        echo "${message2}" >> "${file}"
  #    fi
  #    warn=no
  #  args:
  #    executable: /bin/bash
  - name: set java_home PATH in environment variable
    tags: install,setenv
    lineinfile:
      line: "export JAVA_HOME={{java_home}}"
      dest: "{{ '~/.bashrc' }}"
      regexp: "^export JAVA_HOME=.*/java/.*"
      insertbefore: "^[ \t]*#.*magneto:END"

  - name: set java_bin PATH in environment variable
    tags: install,setenv
    lineinfile:
      line: "export PATH=${JAVA_HOME}/bin:${PATH}"
      dest: "{{ '~/.bashrc' }}"
      regexp: "^export PATH=.{JAVA_HOME}/bin.*"
      insertbefore: "^[ \t]*#.*magneto:END"
