---


- name: conf default.conf
  tags: conf
  sudo: yes
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf

- name: check nginx status
  tags: conf
  clueserv: name=nginx path={{ nginx_home }} state=status
  register: nginx_status

- name: restart nginx
  tags: conf
  shell: echo "restart nginx"
  when:  nginx_status.status == 'started'
  notify:
    - restart nginx
