spring:
  application:
    name: datamaster-cleaner
  profiles:
    # active env
    active: dev
  datasource:
    schema: classpath:sql/schema.sql
    initialize: true
    continue-on-error: false
    name: datamaster
    # mysql username
    username: @jdbc.username@
    # Mysql password
    password: @jdbc.password@
    # Mysql connection url
    url: jdbc:mysql://@jdbc.ip@/datamaster?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8
    tomcat:
      max-active: 20
      max-idle: 20
      max-wait: 60000
      min-idle: 1
  aop:
    auto: true
    proxy-target-class: true
  jackson:
    default-property-inclusion: non_null
logging:
    path: /data/datamaster/log
    level:
         root: info
    config: classpath:logback-spring.xml
server:
  context-path: /cleaner
  port: 7776
  tomcat:
    uri-encoding: utf-8

mybatis:
  configuration:
    map-underscore-to-camel-case: true

esconfig:
 clusterName: @es.clusterName@
 # ES ip
 clusterIp: @es.clusterIp@
 shardsNum: 5
 replicasNum: 1
 parallelism: 8

kafkaConfig:
  schemaRegServer: @kafka.schemaRegServer@
  zkConfig:
    zkUrl: @kafka.zkUrl@
    sessionTimeout: 5000
    connectionTimeout: 5000

hdfsConfig:
  server: @hdfs.server@
  port: @hdfs.port@
  clusterName: @hdfs.clusterName@
  username: @hdfs.username@
  zkConfig:
    zkUrl: @hdfs.zkUrl@
    sessionTimeout: 5000
    connectionTimeout: 5000

---
spring:
  profiles: dev

---
spring:
  profiles: beta

---
spring:
  profiles: prod
