spring:
  profiles:
    # active env
    active: dev
  datasource:
    schema: classpath:sql/drop.sql,classpath:sql/schema.sql
    data: classpath:sql/data.sql
    initialize: true
    continue-on-error: false
    name: datamaster_integ
    username: datamaster
    password: datA123!@#
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.24.8.115/datamaster_integ?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    sql-script-encoding: UTF-8
    tomcat:
      max-active: 20
      max-idle: 20
      max-wait: 60000
      min-idle: 1
  aop:
    auto: true
    proxy-target-class: true
logging:
    path: /data/datamaster/log
    level:
         root: info
    config: classpath:logback-spring.xml
server:
  context-path: /cleaner
  port: 7776
  tomcat:
    uri-encoding: utf-8

mybatis:
  configuration:
    map-underscore-to-camel-case: true


esconfig:
 clusterName: datamaster
 clusterIp: 172.24.8.115
 shardsNum: 5
 replicasNum: 1
 parallelism: 2

kafkaConfig:
  schemaRegServer: 172.24.8.115
  zkConfig:
    zkUrl: 172.24.8.115
    sessionTimeout: 5000
    connectionTimeout: 5000

mysqlConfig:
  host: 172.24.8.115
  port: 3306
  database: datamaster_integ
  username: datamaster
  password: datA123!@#

hdfsConfig:
  server: 172.24.8.115
  port: 9000
  clusterName: datamaster
  username: magneto
  zkConfig:
    zkUrl: 172.24.8.115
    sessionTimeout: 5000
    connectionTimeout: 5000
