spring:
  application:
    name: scheduler-service
  profiles:
    # active env
    active: dev
logging:
    path: /data/scheduler/log
    level:
         root: info
    config: classpath:logback-spring.xml
server:
  context-path: /scheduler
  port: 7778
  tomcat:
    uri-encoding: utf-8

