---

- name: clear datas
  tags: danger,clear
  shell: rm -r {{ item }}/*
  register: clearstat
  with_items:
    - "{{ confluent_data_root }}"
  changed_when: clearstat.rc == 0
  failed_when: False

