---

- name: config kafka
  tags: conf
  template: src=kafka/{{ item.tmpl }} dest={{ confluent_home }}/etc/kafka/{{ item.dst }}
  with_items:
    - { tmpl: server.properties.j2, dst: server.properties }
  register: confstat

- name: config control
  tags: conf
  template: src={{ item.tmpl }} dest={{ confluent_home }}/control/{{ item.dst }}
  with_items:
    - { tmpl: control_conf.py.j2, dst: control_conf.py }

- name: check service status
  tags: conf
  clueserv: name=confluent path={{ confluent_home }} state=status
  register: servstat
  when: confstat.changed

  #- debug: msg="{{ servstat.status }}"
  #  tags: conf
  #  when: confstat.changed

- name: notify restart
  shell: echo "config changed, restart service ..."
  tags: conf
  when:
    - confstat.changed
    - servstat.status == "started"
  notify:
    - restart confluent

