package cn.deepclue.scheduler;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@SpringBootApplication
public class SchedulerClient {
    public static void main(String[] args) {
        SpringApplication.run(SchedulerClient.class, args);
    }
}
